kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mentalarts
networking:
  ipFamily: dual
nodes:
- role: control-plane
  image: kindest/node:v1.26.3
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.3
- role: worker
  image: kindest/node:v1.26.3
- role: worker
  image: kindest/node:v1.26.3
